=== zatopek/tracfone/Workspace/TracfoneAD/WebContent/SYSTEM/resources/xmlValidators/environmentVariables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
  <xs:element name="variables">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="variable"/>
      </xs:sequence>
      <xs:attribute name="creationDate" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="variable">
    <xs:complexType>
      <xs:attribute name="runtimeSource" type="xs:string"/>
      <xs:attribute name="runtimeMethod" type="xs:string"/>
      <xs:attribute name="name"  use="required" type="xs:string"/>
      <xs:attribute name="group" type="xs:string"/>
      <xs:attribute name="designtimeSource" type="xs:string"/>
      <xs:attribute name="designtimeMethod" type="xs:string"/>
      <xs:attribute name="runtimeInlineValue" type="xs:string" />
      <xs:attribute name="designtimeInlineValue" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zatopek/tracfone/Workspace/TracfoneAD/WebContent/USER/resources/dynamicViews/environmentVariables/variables.xml
<?xml version="1.0" ?>
<variables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\SYSTEM\resources\xmlValidators\environmentVariables.xsd"
	creationDate="Thu Aug 18 14:36:49 IDT 2011">
	
	<!-- NOTE: Jacada recommends updating this file using the Environment Variables Configuration dialog only  -->
	
	<variable name="loadDisposition" 
		group="pushKeywords"
		runtimeInlineValue="loadDisposition"
		designtimeInlineValue="loadDisposition"
	/>
	<variable name="sessionId" 
		runtimeSource="sessionInformation"
		group="sessionInfo"
		runtimeMethod="getSessionId"
		designtimeInlineValue="dummySessionId"
	/>
	<variable name="updateCTIClient" 
		group="pushKeywords"
		runtimeInlineValue="UpdateCTIClient"
		designtimeInlineValue="UpdateCTIClient"
	/>
	<variable name="agentId" 
		runtimeSource="agentInformation"
		group="sessionInfo"
		runtimeMethod="getAgentId"
		designtimeInlineValue="workspace"
	/>
	<variable name="unloadScript" 
		group="pushKeywords"
		runtimeInlineValue="unload_script"
		designtimeInlineValue="unload_script"
	/>
	<variable name="projectName" 
		runtimeSource="projectId"
		group="projectInfo"
		runtimeMethod="toString"
		designtimeInlineValue="Jacada WorkSpace"
		designtimeSource="projectId"
		designtimeMethod="toString"
	/>
	<variable name="loadScript" 
		group="pushKeywords"
		runtimeInlineValue="call_script_name"
		designtimeInlineValue="call_script_name"
	/>
	<variable name="Jacada WorkFlow URL" 
		runtimeSource="workflowServerURL"
		group="projectInfo"
		runtimeMethod="toString"
		designtimeSource="workflowServerURL"
		designtimeMethod="toString"
	/>
	
</variables>
