=== zatopek/tracfone/Workspace/TracfoneAD/WebContent/SYSTEM/resources/xmlValidators/smartPad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="shortcut">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required"/>
			<xs:attribute name="alt" type="xs:boolean" use="required"/>
			<xs:attribute name="ctrl" type="xs:boolean" use="required"/>
			<xs:attribute name="shift" type="xs:boolean" use="required"/>
			<xs:attribute name="win" type="xs:boolean" use="required"/>
			<xs:attribute name="display" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="shortcuts">
		<xs:complexType>
			<xs:choice  maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="shortcut"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
  
  <!-- definition of root element --> 
	<xs:element name="smartPad">
		<xs:complexType>
			<xs:choice  maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="shortcuts"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== zatopek/tracfone/Workspace/TracfoneAD/WebContent/USER/portlets/smartPad/smartPad.xml
<?xml version="1.0" encoding="UTF-8"?>
<smartPad  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\SYSTEM\resources\xmlValidators\smartPad.xsd">
	<shortcuts>
		<shortcut key="1" alt="false" ctrl="true" shift="false" win="false" display="CTRL+1"/>
		<shortcut key="1" alt="true" ctrl="true" shift="false" win="false" display="CTRL+ALT+1"/>
		<shortcut key="2" alt="false" ctrl="true" shift="false" win="false" display="CTRL+2"/>
		<shortcut key="2" alt="true" ctrl="true" shift="false" win="false" display="CTRL+ALT+2"/>
		<shortcut key="3" alt="false" ctrl="true" shift="false" win="false" display="CTRL+3"/>
		<shortcut key="3" alt="true" ctrl="true" shift="false" win="false" display="CTRL+ALT+3"/>
		<shortcut key="4" alt="false" ctrl="true" shift="false" win="false" display="CTRL+4"/>
		<shortcut key="4" alt="true" ctrl="true" shift="false" win="false" display="CTRL+ALT+4"/>
		<shortcut key="3" alt="true" ctrl="false" shift="true" win="false" display="ALT+SHIFT+3"/>
		<shortcut key="q" alt="false" ctrl="false" shift="false" win="true" display="WIN+Q"/>
		<shortcut key="w" alt="true" ctrl="true" shift="true" win="false"/>
		<shortcut key="e" alt="true" ctrl="true" shift="true" win="false"/>
	</shortcuts>
</smartPad>
